version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.springframework:spring-webmvc
    versions:
    - 5.0.5.RELEASE
    - 5.1.5.RELEASE
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.0.5.RELEASE
    - 5.1.5.RELEASE
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.0.5.RELEASE
    - 5.1.5.RELEASE
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.0.5.RELEASE
    - 5.1.5.RELEASE
