language: java
jdk:
  - oraclejdk8
#  - oraclejdk9
  - openjdk8
#  - openjdk9

before_install:
  - chmod +x mvnw

#  Email notifications
notifications:
  email:
    recipients:
      - pawel.linkshell@gmail.com
    on_succes: never    # default: change
    on_failure: always  # default: always

# SonarCloud
addons:
  sonarcloud:
    organization: "pawellinkshell-github" # the key of the organization
    token:
      secure: "YC5ymcfCn89ttfnHila8WNrN5yXy/to1wJiCllQUqGjGDEaPvSrbvzSuFW6pmeUo97OF2ykn+W4tMpRWxBIM6fVOnSEgcnJvfNbp/bAOSuL4EuQjGqKfzCcePc0aFTEhKPSvPeqsx0Iewr6bZu4vhd1koEVlrVo9HxlWwpDeWKR2RG4TkjneQG8spGAm0Xef7Q9NVuHCRSGlc+prOSZORXYOs5UlVAWlGt5IB05h+JcSL6s0vSJTGfNb8N1rxwJ0bjFXEhN0JlAjAsI2fap1Yi+3Fdb11M6y+YEDyLEaaMCQtDoKP4l20+/izagXPT1Z1uqynIEAWWymVajVlEZE1UNe7layqo3/tblVxDigXT/0ZEB3xA2GxavQfssTOpLO/8BnjC4vNaeQAKd5zu2ZV6benaGwd2/wesm4fOcZcz6wJq0MMvs2+OjsVEFKZJaLx+G1b0ler6iUye+qf5YnQnr00gnU8HrT00tLprAW45gYSvpPXb+/QFo55Ion2WEZIybWnfI45Sf7DbPF+tBvb+0pTdLvjGlkRn5y3N1DSTuDLlPsfWdrspXKHQkwuBSIwVW8n0kSZE4jdtj3bEMFX7klDkSvo8hV7XGKJjOxemft7ZfIxMjQGlOZZzJvbAnCkJ4Pm8+I57K88/vCLVXgetloJ93xMNg6XvOTvU7ZFJc=" # encrypted value of your token
    branches:
      - heroku
      - release
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f42f4462-3ad7-443d-b7fc-fe684a32b6f8